#!/usr/bin/env python3
"""
generate_paysh.py <service.json> [output.yml]

Generates a pay.sh provider YAML spec from a service config.
Output is ready to PR to solana-foundation/pay-skills under
providers/{name}/{name}.yml
"""

import json, sys, os
from pathlib import Path

def bail(msg: str):
    print(f"ERROR: {msg}", file=sys.stderr)
    sys.exit(1)

def load_config(path: str) -> dict:
    try:
        with open(path) as f:
            return json.load(f)
    except FileNotFoundError:
        bail(f"Config file not found: {path}")
    except json.JSONDecodeError as e:
        bail(f"Invalid JSON in {path}: {e}")

PAYSH_CATEGORIES = {
    "ai_ml", "cloud", "compute", "data", "devtools", "finance",
    "identity", "maps", "media", "messaging", "productivity",
    "search", "security", "shopping", "storage", "translation", "other",
}

CATEGORY_MAP = {
    # x402scan → pay.sh
    "data":          "data",
    "finance":       "finance",
    "compute":       "compute",
    "ai_ml":         "ai_ml",
    "developer-tools":"devtools",
    "devtools":      "devtools",
    "search":        "search",
    "storage":       "storage",
    "media":         "media",
    "messaging":     "messaging",
    "security":      "security",
    "identity":      "identity",
    "maps":          "maps",
    "travel":        "other",
    "social":        "other",
    "shopping":      "shopping",
    "communication": "messaging",
    "other":         "other",
}

def pick_paysh_category(categories: list) -> str:
    for cat in categories:
        mapped = CATEGORY_MAP.get(cat, "other")
        if mapped in PAYSH_CATEGORIES:
            return mapped
    return "other"

def price_in_dollars(amount_str: str) -> float:
    """Convert micro-USDC string to dollars."""
    return int(amount_str) / 1_000_000

def yaml_str(s: str, indent: int = 0) -> str:
    s = str(s)
    needs_quote = any(c in s for c in [':', '#', '{', '}', '[', ']', ',', '&', '*', '?', '|', '<', '>', '=', '!', '%', '@', '`', "'", '"', '\n'])
    pad = " " * indent
    if needs_quote:
        escaped = s.replace("'", "''")
        return f"{pad}'{escaped}'"
    return f"{pad}{s}"

def generate_yaml(c: dict) -> str:
    price     = c["price"]
    amount_usd = price_in_dollars(str(price["amount"]))
    category  = pick_paysh_category(c.get("categories", ["other"]))
    base_url  = c["baseUrl"].rstrip("/")
    name      = c["name"]
    version   = c.get("version", "v1")
    contact   = c.get("contact", {})
    docs      = c.get("docs", {})

    lines = [
        f"# pay.sh provider spec — {c['title']}",
        f"# Auto-generated by x402-publish skill",
        f"# PR to: solana-foundation/pay-skills → providers/{name}/{name}.yml",
        f"",
        f"name: {name}",
        f"subdomain: {name}",
        f"title: {yaml_str(c['title'])}",
        f"description: {yaml_str(c['description'])}",
        f"category: {category}",
        f"version: {version}",
        f"",
        f"routing:",
        f"  type: proxy",
        f"  url: {base_url}/",
        f"",
        f"operator:",
        f"  currencies:",
        f"    usd: ['USDC']",
        f"  network: mainnet",
        f"  recipient: '{price['payTo']}'",
    ]

    if contact.get("email"):
        lines += ["", f"# Contact: {contact['email']}"]
    if docs.get("homepage"):
        lines += [f"# Homepage: {docs['homepage']}"]

    lines += ["", "endpoints:"]

    # Free endpoints first
    for ep in c.get("freeEndpoints", []):
        method = ep.get("method", "GET").upper()
        path   = ep["path"].lstrip("/")
        lines += [
            f"  - method: {method}",
            f"    path: '{path}'",
            f"    description: {yaml_str(ep.get('summary', path))}",
        ]

    # Gated endpoints
    for ep in c["endpoints"]:
        method = ep.get("method", "GET").upper()
        path   = ep["path"].lstrip("/")
        lines += [
            f"  - method: {method}",
            f"    path: '{path}'",
            f"    description: {yaml_str(ep.get('summary', path))}",
            f"    metering:",
            f"      dimensions:",
            f"        - direction: usage",
            f"          unit: requests",
            f"          scale: 1",
            f"          tiers:",
            f"            - price_usd: {amount_usd}",
        ]

    return "\n".join(lines) + "\n"

def main():
    if len(sys.argv) < 2:
        bail("Usage: generate_paysh.py <service.json> [output.yml]")

    config_path = sys.argv[1]
    c = load_config(config_path)

    # Basic validation
    for field in ["name", "title", "description", "baseUrl", "price", "endpoints"]:
        if field not in c:
            bail(f"Missing required field: {field}")
    if not isinstance(c["price"], dict):
        bail("price must be an object with amount and payTo")
    for field in ["amount", "payTo"]:
        if c["price"].get(field) in (None, ""):
            bail(f"Missing required field: price.{field}")
    try:
        int(str(c["price"]["amount"]))
    except ValueError:
        bail(f"price.amount must be an integer micro-USDC value, got {c['price']['amount']!r}")
    methods = {"GET", "PUT", "POST", "DELETE", "OPTIONS", "HEAD", "PATCH", "TRACE"}
    for label in ["endpoints", "freeEndpoints"]:
        for ep in c.get(label, []):
            if not isinstance(ep, dict) or not isinstance(ep.get("path"), str) or not ep["path"].strip():
                bail(f"{label} entry is missing a non-empty path")
            if str(ep.get("method", "GET")).upper() not in methods:
                bail(f"{label} {ep['path']}: unsupported HTTP method {ep.get('method')!r}")

    yaml_out = generate_yaml(c)

    if len(sys.argv) >= 3:
        out_path = sys.argv[2]
    else:
        out_dir  = Path(config_path).parent
        out_path = out_dir / f"{c['name']}.yml"

    with open(out_path, "w") as f:
        f.write(yaml_out)

    name = c["name"]
    print(f"✓  pay.sh YAML → {out_path}")
    print(f"   Category: {pick_paysh_category(c.get('categories', ['other']))}")
    print(f"   {len(c['endpoints'])} gated endpoints @ ${price_in_dollars(str(c['price']['amount'])):.4g} USDC each")
    print()
    print("Next steps:")
    print(f"  1. Fork https://github.com/solana-foundation/pay-skills")
    print(f"  2. Copy {out_path} → providers/{name}/{name}.yml")
    print(f"  3. Open a PR with title: 'feat: add {c['title']} provider'")

if __name__ == "__main__":
    main()
