#!/usr/bin/env bash
set -euo pipefail

echo "🎬 Clawdrop Demo Recording Guide"
echo "================================="
echo ""
echo "Prerequisites:"
echo "  - OBS Studio installed (https://obsproject.com)"
echo "  - Synapse Explorer open: https://explorer.oobeprotocol.ai"
echo "  - Twitter @ClawdropSignals profile open"
echo "  - Telegram @ClawdropSignals channel open"
echo "  - Terminal ready with sqlite3 and curl"
echo "  - Solscan.io open in browser"
echo ""
echo "Segment 1 (30s): Agent Registration"
echo "  1. Switch to Synapse Explorer"
echo "  2. Scroll to show 3 Clawdrop agents"
echo "  3. Click one agent, show capabilities"
echo "  Narration: '3 autonomous agents registered on Solana SAP...'"
echo ""
echo "Segment 2 (30s): Signal Generation"
echo "  1. Switch to terminal showing agent logs"
echo "  2. Highlight line: 'Signal generated: BUY \$42.50, confidence 0.85'"
echo "  3. Show timestamp"
echo "  Narration: 'Agent generates trading signal every hour...'"
echo ""
echo "Segment 3 (60s): Distribution in Action"
echo "  1. Switch to Twitter @ClawdropSignals"
echo "  2. Scroll to latest tweet (match signal from Segment 2)"
echo "  3. Show likes/retweets"
echo "  4. Switch to Telegram @ClawdropSignals"
echo "  5. Show same signal message"
echo "  6. Show member count (100+)"
echo "  Narration: 'Real-time distribution within 5 minutes...'"
echo ""
echo "Segment 4 (30s): Proof of Volume"
echo "  1. Terminal: sqlite3 query showing 150+ payments"
echo "  2. Copy tx signature from DB"
echo "  3. Paste into Solscan, show transaction details"
echo "  Narration: 'All payments settled on-chain via x402...'"
echo ""
echo "Upload:"
echo "  - Export from OBS as MP4 (1080p)"
echo "  - Upload to YouTube (unlisted or public)"
echo "  - Copy link for bounty submission"
echo ""
