module.exports = {
  apps: [
    {
      name: 'oobe-backend',
      script: 'npx',
      args: 'tsx src/server.ts',
      cwd: '/Users/luisploennig/Colosseum/hfsp-labs-colosseum/packages/oobe-bounty',
      interpreter: 'none',
      env: { NODE_ENV: 'production' },
      watch: false,
      max_memory_restart: '512M',
      restart_delay: 5000,
      max_restarts: 10,
      min_uptime: '30s',
      log_file: '/Users/luisploennig/Colosseum/hfsp-labs-colosseum/packages/oobe-bounty/logs/backend.log',
      error_file: '/Users/luisploennig/Colosseum/hfsp-labs-colosseum/packages/oobe-bounty/logs/backend-err.log',
      merge_logs: true,
      time: true,
    },
    {
      name: 'oobe-dist',
      script: 'npx',
      args: 'tsx src/distribution/start-prod.ts',
      cwd: '/Users/luisploennig/Colosseum/hfsp-labs-colosseum/packages/oobe-bounty',
      interpreter: 'none',
      env: { NODE_ENV: 'production' },
      watch: false,
      max_memory_restart: '256M',
      restart_delay: 8000,
      max_restarts: 10,
      min_uptime: '30s',
      log_file: '/Users/luisploennig/Colosseum/hfsp-labs-colosseum/packages/oobe-bounty/logs/dist.log',
      error_file: '/Users/luisploennig/Colosseum/hfsp-labs-colosseum/packages/oobe-bounty/logs/dist-err.log',
      merge_logs: true,
      time: true,
    },
  ],
};
