server {
    listen 80;
    server_name store.hfsp.cloud;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl http2;
    server_name store.hfsp.cloud;

    ssl_certificate     /etc/letsencrypt/live/store.hfsp.cloud/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/store.hfsp.cloud/privkey.pem;
    ssl_protocols       TLSv1.2 TLSv1.3;
    ssl_ciphers         HIGH:!aNULL:!MD5;

    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
    add_header X-Frame-Options DENY;
    add_header X-Content-Type-Options nosniff;

    # No access log — privacy
    access_log off;
    error_log /var/log/nginx/store-hfsp-error.log warn;

    location / {
        proxy_pass         http://127.0.0.1:3005;
        proxy_http_version 1.1;
        proxy_set_header   Host $host;
        proxy_set_header   X-Real-IP "";
        proxy_set_header   X-Forwarded-For "";
        proxy_set_header   X-Forwarded-Proto "";
        proxy_read_timeout 30s;
    }
}
